[package]
name = "estienne"
version = "0.8.0-alpha"
edition = "2024"

[lib]
name = "est"

[dependencies]
thiserror ="2.0"
regex = "1"
lazy_static = "1.5.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
